service: uisheet

custom:
  bucket: uisheet
  warmup:
    getWarm:
      enabled: true
  webpack:
    includeModules:
      forceInclude:
        - sib-api-v3-sdk
  customDomains:
    - http:
        domainName: exhaustbarn.com
        basePath: ''
        endpointType: 'regional'
    - http:
        domainName: plazamuffler.com
        basePath: ''
        endpointType: 'regional'

provider:
  name: aws
  stage: dev
  runtime: nodejs12.x
  region: us-west-1
  memorySize: 512
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource:
            - "*" 
        - Effect: Allow
          Action:
            - s3:ListBucket
            - s3:GetObject
            - s3:GetObjectAcl
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:DeleteObject
            - s3:DeleteObjectAcl
          Resource:
            - "arn:aws:s3:::${self:custom.bucket}"
            - "arn:aws:s3:::${self:custom.bucket}/*"
  apiGateway:
    binaryMediaTypes:
      - 'text/html'
      - 'image/*'
      - 'image/webp'
      - 'video/mp4'
  environment:
    DB: ${file(./variables.json):DB}
    SSKEY: ${file(./variables.json):SSKEY}
    VERIFY: ${file(./variables.json):VERIFY}
    SIB: ${file(./variables.json):SIB}
    BTMERCHANTID: ${file(./variables.json):BT.MERCHANTID}
    BTPUBLIC: ${file(./variables.json):BT.PUBLIC}
    BTPRIVATE: ${file(./variables.json):BT.PRIVATE}
    BTTOKEN: ${file(./variables.json):BT.TOKEN}
    BUCKET: ${self:custom.bucket}

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-domain-manager
  - serverless-plugin-warmup
    
functions:
  bulk:
    handler: handler.bulk
    timeout: 900
    warmup:
      getWarm:
        enabled: false
  get:
    handler: handler.port
    timeout: 30
    events:
      - http:
          method: any
          path: /
          cors: true
      - http:
          method: any
          path: /{site}
          cors: true
      - http:
          method: any
          path: /{site}/{chain}
          cors: true
      - http:
          method: any
          path: /{site}/{chain}/{arg1}
          cors: true
      - http:
          method: any
          path: /{site}/{chain}/{arg1}/{arg2}
          cors: true
      - s3:
          bucket: ${self:custom.bucket}
